### ISSUE TITLE
thead not styled

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-css#36]
Hi,

Not sure if its bad practice (on my part) or not but I usually define my table header using the thead tag. This isnt styled by denali css in the current release. The styling only seems to apply to th tags under tbody.

Example;

```
<table>
  <thead>
    <tr>
      <th>Month</th>
      <th>Savings</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>January</td>
      <td>$100</td>
    </tr>
    <tr>
      <td>February</td>
      <td>$80</td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td>Sum</td>
      <td>$180</td>
    </tr>
  </tfoot>
</table>
```

**Comment by chasturansky** [comment]
Hello, 

Thank you for pointing this out. We chose to not use thead, tbody, and tfoot in the current implementation because we knew that we would not be supporting scrolling in tables yet. This let us style a table quickly and to get something out for our developers, while we worked on a solution for scrolling in tables. 

We plan to roll out a revamped table and a whole lot of helpers for it in the coming months. Stay tuned.

Thanks,
Chas T.
